# kubetpl:syntax:go-template
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-cm
  namespace: {{ .Values.sawtooth.namespace}}
data:
  telegraf.conf: |
    [global_tags]
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      quiet = false
      logfile = ""
      hostname = "$NODE_NAME"
      omit_hostname = false
    [[outputs.influxdb]]
      urls = ["{{if .Values.sawtooth.opentsdb.url}}{{.Values.sawtooth.opentsdb.url}}{{else}}http://influxdb.{{.Values.sawtooth.namespace}}:8086{{end}}"]
      database = "{{.Values.sawtooth.opentsdb.db}}"
      precision = "s"
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
    [[inputs.diskio]]
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    [[inputs.swap]]
    [[inputs.system]]
---
