# kubetpl:syntax:go-template
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.sawtooth.networkName}}-sa
  namespace: {{.Values.sawtooth.namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Values.sawtooth.networkName}}:role
  namespace: {{.Values.sawtooth.namespace}}
rules:
  - apiGroups: ["","apps/v1"] # "" refers to the core API group
    resources: ["services", "statefulsets.apps","endpoints", "nodes", "pods"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["","apps/v1"] # "" refers to the core API group
    resources: ["configmaps"]
    verbs: ["get", "create", "list", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Values.sawtooth.namespace}}:{{.Values.sawtooth.networkName}}:clusterrole
rules:
  - apiGroups: ["","apps/v1"] # "" refers to the core API group
    resources: ["statefulsets.apps", "nodes", "pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{.Values.sawtooth.namespace}}:{{.Values.sawtooth.networkName}}
  namespace: {{.Values.sawtooth.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.Values.sawtooth.networkName}}:role
subjects:
- kind: ServiceAccount
  name: {{.Values.sawtooth.networkName}}-sa
  namespace: {{.Values.sawtooth.namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.sawtooth.namespace}}:{{.Values.sawtooth.networkName}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Values.sawtooth.namespace}}:{{.Values.sawtooth.networkName}}:clusterrole #is this a terinary??
subjects:
- kind: ServiceAccount
  name: {{.Values.sawtooth.networkName}}-sa
  namespace: {{.Values.sawtooth.namespace}}

---
