{{- if .Values.trigger.ingress.enabled -}}
{{ $svcName := .Values.sawtooth.networkName }}
{{ $svcPort := .Values.sawtooth.ports.trigger_http_port }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Values.sawtooth.networkName}}-jsonapi
  {{- with .Values.trigger.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.trigger.ingress.tls }}
  tls:
  {{- range .Values.trigger.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.trigger.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $svcName }}-daml-rpc
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
