# kubetpl:syntax:go-template
{{ if .Values.sawtooth.daml.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.sawtooth.networkName}}-daml-rpc
  namespace: {{.Values.sawtooth.namespace}}
  labels:
    app: {{.Values.sawtooth.networkName}}-daml-rpc
    daml: {{.Values.sawtooth.networkName}}-daml-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.sawtooth.networkName}}-daml-rpc
      daml: {{.Values.sawtooth.networkName}}-daml-rpc
  template:
    metadata:
      labels:
        app: {{.Values.sawtooth.networkName}}-daml-rpc
        daml: {{.Values.sawtooth.networkName}}-daml-rpc
    spec:
      serviceAccountName: {{.Values.sawtooth.networkName}}-sa
      containers:
      - name: postgres
        image: {{.Values.images.postgres}}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      - name: daml-rpc
        image: {{.Values.images.daml_rpc}}
        command: [ "bash", "-xc"]
        args:
        - |
            sleep {{.Values.sawtooth.client_wait}}
            /opt/sawtooth-daml-rpc/entrypoint.sh --port {{.Values.sawtooth.ports.damlrpc}} \
                --connect tcp://{{.Values.sawtooth.networkName}}-validator:{{.Values.sawtooth.ports.sawcomp}} \
                --jdbc-url jdbc:postgresql://localhost/postgres?user=postgres \
                --participant-id {{.Values.sawtooth.networkName}} \
                {{ if .Values.sawtooth.daml.extra_args.enabled }}{{.Values.sawtooth.daml.extra_args.arg_str}}{{ else }}--auth wildcard {{ end }}
        resources:
          limits:
            cpu: "250m"
          requests:
            cpu: "50m"
        ports:
        - containerPort: {{.Values.sawtooth.ports.damlrpc}}
          name: daml-ledger-api
        volumeMounts:
        - mountPath: "/etc/sawtooth"
          name: sawtooth-etc
      volumes:
        - name: sawtooth-etc
          hostPath:
            type: DirectoryOrCreate
            path: {{.Values.sawtooth.volumes.hostPathBaseDir}}/{{.Values.sawtooth.namespace}}/{{.Values.sawtooth.networkName}}/sawtooth-etc
{{ end }}
---
