{{- $serviceName := (include "daml.service.name" . ) -}}
{{- $ingressName := printf "%s" $serviceName -}}
{{- $servicePort := .Values.port | int -}}
{{ include "lib.ingress" (dict "ingressName" $ingressName "ingress" .Values.ingress "serviceName" $serviceName "servicePort" $servicePort "context" $) }}
