---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{include "common.names.fullname" .}}
  labels: {{ include "daml.labels" . | nindent 4 }}
rules:
  - apiGroups: ["","apps/v1"] # "" refers to the core API group
    resources: ["secrets"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{include "common.names.fullname" .}}
  labels: {{ include "daml.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{include "common.names.fullname" .}}
subjects:
- kind: ServiceAccount
  name: {{ include "lib.serviceAccountName" . }}
---
