---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.sawtooth.networkName}}-sa
  namespace: {{.Values.sawtooth.namespace}}
automountServiceAccountToken: false
{{ if .Values.imagePullSecrets.enabled }}
imagePullSecrets:
{{range .Values.imagePullSecrets.value }}
  - name: {{ .name }}
{{ end }}
{{ end }}
