---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "daml.trigger.service.name" . }}
  labels: {{ include "daml.labels" . | nindent 4 }}
    component: triggers
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  selector: {{ include "daml.labels.matchLabels" . | nindent 4 }}
    component: triggers
