{{$peering:= .Values.sawtooth.dynamicPeering}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.sawtooth.networkName}}-rest-api
  namespace: {{.Values.sawtooth.namespace}}
  labels:
    app: {{.Values.sawtooth.networkName}}-validator
    component: sawtooth
spec:
  sessionAffinity: ClientIP
  ports:
  - port: {{.Values.sawtooth.ports.rest}}
    protocol: TCP
    targetPort: {{.Values.sawtooth.ports.rest}}
    name: rest-api
  selector:
    app: {{.Values.sawtooth.networkName}}-validator
---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.sawtooth.networkName}}-validator
  namespace: {{.Values.sawtooth.namespace}}
  labels:
    app: {{.Values.sawtooth.networkName}}-validator
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{.Values.sawtooth.ports.rest}}
    protocol: TCP
    targetPort: {{.Values.sawtooth.ports.rest}}
    name: rest-api
  - port: {{.Values.sawtooth.ports.sawnet}}
    protocol: TCP
    targetPort: {{.Values.sawtooth.ports.sawnet}}
    name: sawnet
  - port: {{.Values.sawtooth.ports.sawcomp}}
    protocol: TCP
    targetPort: {{.Values.sawtooth.ports.sawcomp}}
    name: sawcomp
  selector:
    app: {{.Values.sawtooth.networkName}}-validator
