{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentd.serviceAccountName" . }}
  labels: {{- include "fluentd.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{- include "fluentd.tplValue" (dict "value" .Values.serviceAccount.annotations "context" $) | nindent 4 }}
  {{- end }}
{{- end -}}
