---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "besu.fullname" . }}-role
  namespace: {{.Release.Namespace}}
  labels:
{{ include "besu.labels" . | indent 4 }}
rules:
  - apiGroups:
      - "" # "" refers to the core API group
    resources:
      - secrets
      - configmaps
    verbs:
      - create
      - get
      - list
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
