apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "besu.fullname" . }}-genesis
  namespace: {{.Release.Namespace}}
  labels:
{{ include "besu.labels" . | indent 4 }}
  annotations:
    helm.sh/hook-delete-policy: "hook-succeeded"
spec:
  backoffLimit: 3
  completions: 1
  template:
    metadata:
      labels:
{{ include "besu.selectorLabels" . |indent 8 }}
    spec:
      serviceAccountName: {{ include "besu.serviceAccountName" . }}
      restartPolicy: Never
      {{ if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
      {{range .Values.imagePullSecrets.value }}
        - name: {{ .name }}
      {{ end }}
      {{ end }}
      containers:
        - name: genesis
          image: "{{.Values.besu.image.repository }}:{{ .Values.besu.image.tag }}"
          securityContext:
            runAsUser: 0
          imagePullPolicy: {{ .Values.besu.image.imagePullPolicy }}
          volumeMounts:
            - name: genesis-config
              mountPath: /genesis-config
          command:
            - bash
            - -c
          args:
            - |
              curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl \
                -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
              chmod +x ./kubectl
              ./kubectl get cm {{ include "besu.fullname" .}}-genesis
              if [ $? -eq 0 ]; then
                exit
              fi
              mkdir -p /tmp/genesis
              /opt/besu/bin/besu operator generate-blockchain-config \
                --config-file=/genesis-config/config.json --to=/tmp/genesis
              ./kubectl create configmap --namespace {{ .Release.Namespace }} {{ include "besu.fullname" . }}-genesis --from-file=genesis.json=/tmp/genesis/genesis.json

              count=0
              secret_args=()
              pubkey_args=()
              enode_args=()
              for f in /tmp/genesis/keys/*; do
                if [ -d ${f} ]; then
                  sed 's/^0x//' ${f}/key.pub > ${f}/enode.key
                  secret_args[$count]="--from-file={{include "besu.fullname" .}}-$count=${f}/key.priv"
                  pubkey_args[$count]="--from-file={{include "besu.fullname" .}}-$count.pub=${f}/key.pub"
                  enode_args[$count]="--from-file={{include "besu.fullname" .}}-$count.enode=${f}/enode.key"
                  count=$((count + 1))
                fi
              done
              ./kubectl create secret generic {{include "besu.fullname" .}}-keys --namespace {{.Release.Namespace}} \
                "${secret_args[@]}" "${pubkey_args[@]}"
              ./kubectl create secret generic {{include "besu.fullname" .}}-pubkeys --namespace {{.Release.Namespace}} \
                "${pubkey_args[@]}"
              ./kubectl create secret generic {{include "besu.fullname" .}}-enode --namespace {{.Release.Namespace}} \
                "${enode_args[@]}"
      volumes:
        - name: genesis-config
          configMap:
            name: {{ include "besu.fullname" . }}-genesis-cm
