apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "daml-on-besu.fullname" .}}
  namespace: {{.Release.Namespace}}
  labels:
{{ include "daml-on-besu.labels" .| indent 4}}
spec:
  replicas: {{.Values.daml.rpcCount}}
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "daml-on-besu.labels" .| indent 6}}
  template:
    metadata:
      labels:
{{ include "daml-on-besu.labels" .| indent 8}}
    spec:
      {{ if .Values.daml.imagePullSecrets }}
      imagePullSecrets:
      {{range .Values.daml.imagePullSecrets }}
        - name: {{ .name }}
      {{ end }}
      {{ end }}
      containers:
      - name: postgres
        image: "{{.Values.postgres.image.repository}}:{{.Values.postgres.image.tag}}"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      - command:
        - bash
        - -xc
        - |
          sleep 120
          /opt/daml-on-besu/rpc/entrypoint.sh \
            --json-rpc-url http://{{include "besu.fullname" .}}-0.{{include "besu.fullname" .}}:{{.Values.besu.rpc.port}} \
            --participant port={{.Values.daml.rpc.port}},address=0.0.0.0,participant-id={{.Values.daml.rpc.participantId}},server-jdbc-url=jdbc:postgresql://localhost/postgres?user=postgres \
            --logging INFO \
            --private-key-file /keys/{{ include "besu.fullname" .}}-0
        image: "{{.Values.daml.image.repository}}:{{.Values.daml.image.tag}}"
        name: daml-on-besu
        ports:
        - containerPort: {{.Values.daml.rpc.port}}
        resources: {}
        volumeMounts:
          - mountPath: /keys
            name: networkkeys-config
            readOnly: true
          - mountPath: /dev/random
            name: dev-random
          - mountPath: /dev/urandom
            name: dev-urandom
      restartPolicy: Always
      volumes:
        - name: networkkeys-config
          secret:
            secretName: {{ include "besu.fullname" .}}-keys
        - name: dev-random
          hostPath:
            path: /dev/random
            type: CharDevice
        - name: dev-urandom
          hostPath:
            path: /dev/urandom
            type: CharDevice
