apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "besu.fullname" . }}-cert
  namespace: {{.Release.Namespace}}
  labels: {{ include "besu.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  backoffLimit: 3
  completions: 1
  template:
    metadata:
      labels: {{ include "besu.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "besu.serviceAccountName" . }}
      automountServiceAccountToken: true
      restartPolicy: Never
      containers:
        - name: openssl
          image: "{{.Values.openssl.image.repository }}:{{ .Values.openssl.image.tag }}"
          imagePullPolicy: {{ .Values.besu.image.imagePullPolicy }}
          volumeMounts:
            - name: scratch
              mountPath: /scratch
          command:
            - sh
            - -ec
          args:
            - |
              mkdir -p /scratch/rsa
              ls -R /scratch
              cd /scratch/rsa
              openssl req -x509 -nodes -days 365 \
                -subj '/C=US/ST=NY/L=Brooklyn/CN=selfsigned' \
                -newkey rsa:1024 -keyout jwt.key -out jwt.crt
              touch /scratch/openssl.done
        - name: k8s
          image: "{{.Values.k8s.image.repository }}:{{ .Values.k8s.image.tag }}"
          imagePullPolicy: {{ .Values.besu.image.imagePullPolicy }}
          volumeMounts:
            - name: scratch
              mountPath: /scratch
          command:
            - sh
            - -c
          args:
            - |
              loops=0
              while [ ! -r /scratch/openssl.done ]; do
                loops=$((loops+1))
                if [ $loops -gt 100 ]; then
                  echo &2>1 "did not find key after 100 seconds"
                  exit 1
                fi
                sleep 1
              done
              kubectl get secret {{ include "besu.fullname" . }}-cert
              if [ $? -eq 0 ]; then
                exit 0
              fi
              kubectl create secret generic \
                --namespace {{ .Release.Namespace }} \
                {{ include "besu.fullname" . }}-cert \
                --from-file=/scratch/rsa
      volumes:
        - name: scratch
          emptyDir: {}
