apiVersion: v1
kind: Service
metadata:
  labels: {{include "daml.labels" . | nindent 4 }}
    component: daml
  name: {{ include "daml.fullname" . }}-rpc
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  selector:
{{include "daml.selectorLabels" . | indent 4 }}
  ports:
    - name: daml-rpc
      port: {{.Values.daml.rpc.port}}
      targetPort: {{.Values.daml.rpc.port}}
    {{- if .Values.daml.jsonapi.enabled }}
    - name: daml-jsonapi
      port: {{.Values.daml.jsonapi.port }}
      targetPort: {{.Values.daml.jsonapi.port}}
    {{- end }}
