apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "daml.fullname" .}}-rpc
  namespace: {{.Release.Namespace}}
  labels: {{- include "daml.labels" .| nindent 4}}
    component: daml
spec:
  replicas: {{.Values.daml.rpcCount}}
  selector:
    matchLabels: {{- include "daml.labels" .| nindent 6}}
      component: daml
  serviceName: {{ include "daml.fullname" . }}-rpc
  template:
    metadata:
      labels: {{- include "daml.labels" .| nindent 8 }}
        component: daml
      {{- if .Values.daml.annotations }}
      annotations:
        {{- toYaml .Values.daml.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "besu.serviceAccountName" . }}
      affinty: {{ include "lib.safeToYaml" .Values.daml.affinity | nindent 8 }}
      containers:
        {{- if .Values.postgres.enabled }}
        - name: postgres
          image: "{{.Values.postgres.image.repository}}:{{.Values.postgres.image.tag}}"
          imagePullPolicy: {{.Values.postgres.image.pullPolicy }}
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          - name: PGDATA
            value: /data/{{.Values.daml.rpc.participantId}}
          volumeMounts:
            - mountPath: /data
              name: "pgdata"
            {{- include "lib.volumeMounts" .Values.extraVolumeMounts | nindent 12 }}
            {{- include "lib.volumeMounts" .Values.daml.extraVolumeMounts | nindent 12 }}
          resources: {{ toYaml .Values.postgres.resources | nindent 12 }}
        {{- end }}
        {{- if .Values.daml.jsonapi.enabled }}
        - name: daml-json-api
          image: "{{.Values.daml.jsonapi.image.repository}}:{{.Values.daml.jsonapi.image.tag}}"
          imagePullPolicy: {{.Values.daml.jsonapi.image.imagePullPolicy}}
          ports:
          - containerPort: {{.Values.daml.jsonapi.port}}
          {{- if .Values.daml.jsonapi.args }}
          args:
            {{- range .Values.daml.jsonapi.args }}
            - {{ . | quote }}
            {{- end -}}
          {{- end }}
          env:
            - name: LEDGER_HOST
              value: localhost
            - name: LEDGER_PORT
              value: {{.Values.daml.rpc.port | quote }}
            - name: HTTP_PORT
              value: {{.Values.daml.jsonapi.port | quote }}
            - name: PACKAGE_RELOAD_INTERVAL
              value: {{.Values.daml.jsonapi.packageReloadInterval | quote }}
            - name: WAIT_FOR_TIME
              value: {{.Values.daml.jsonapi.waitTimeSeconds | quote }}
            {{ if .Values.daml.jsonapi.env }}
            {{- toYaml .Values.daml.jsonapi.env | nindent 12 }}
            {{ end }}
          volumeMounts: {{- toYaml $.Values.daml.extraVolumeMounts | nindent 12 }}
            {{- include "lib.volumeMounts" .Values.extraVolumeMounts | nindent 12 }}
            {{- include "lib.volumeMounts" .Values.daml.extraVolumeMounts | nindent 12 }}
          resources: {{ toYaml .Values.daml.jsonapi.resources | nindent 12 }}
        {{- end }}
        {{ if .Values.besu.privacy.enabled }}
          {{ if .Values.daml.repeater.enabled }}
        - name: repeater
          image: "{{.Values.daml.repeater.repository}}:{{.Values.daml.repeater.tag}}"
          imagePullPolicy: {{.Values.daml.repeater.pullPolicy }}
          command:
            - bash
            - -xc
          args:
            - |
              sleep 90
              /opt/daml-on-besu/repeater/entrypoint.sh \
              --json-config-file /config/config.json \
              --upstream-json-rpc-url http://{{include "besu.fullname" .}}:{{.Values.besu.rpc.port}} \
              --downstream-json-rpc-url http://{{include "besu.fullname" .}}-0:{{.Values.besu.rpc.port}} \
              --private-key-file /keys/{{ include "daml.fullname" .}}-repeater \
              --participant-id {{ include "daml.repeater.participantId" . }}  \
              --logging=debug
          volumeMounts:
            - mountPath: /config
              name: "config"
            - mountPath: /keys
              name: networkkeys-config
              readOnly: true
            - mountPath: /besu-keys
              name: besu-keys
              readOnly: true
            {{- include "lib.volumeMounts" .Values.extraVolumeMounts | nindent 12 }}
            {{- include "lib.volumeMounts" .Values.daml.extraVolumeMounts | nindent 12 }}
          {{ end }}
        {{ end }}
        - name: daml-on-besu
          {{- if .Values.besu.privacy.enabled }}
          image: "{{.Values.daml.privateImage.repository}}:{{.Values.daml.image.tag}}"
          {{- else }}
          image: "{{.Values.daml.image.repository}}:{{.Values.daml.image.tag}}"
          {{- end }}
          imagePullPolicy: {{.Values.daml.image.pullPolicy }}
          ports:
            - containerPort: {{.Values.daml.rpc.port}}
          command:
            - bash
            - -xc
          args:
            - |
              sleep 120
              {{- if .Values.besu.privacy.enabled }}
              /opt/daml-on-besu/private-rpc/entrypoint.sh \
                --use-private-reader-writer true \
                --committer-participant-id {{ include "daml.repeater.participantId" . }} \
                --json-config-file /config/config.json \
              {{- else }}
              /opt/daml-on-besu/rpc/entrypoint.sh \
              {{- end }}
                --json-rpc-url http://{{include "besu.fullname" .}}-0:{{.Values.besu.rpc.port}} \
                --participant port={{.Values.daml.rpc.port}},address=0.0.0.0,participant-id={{.Values.daml.rpc.participantId}},server-jdbc-url=$POSTGRES_URL \
                --private-key-file /keys/{{ include "daml.fullname" .}}-rpc-0 \
                --ledger-id {{.Values.daml.ledgerId }} \
                {{- if .Values.daml.auth.enabled }}
                --auth-jwt-rs256-crt /secrets/jwt/jwt.crt \
                {{- end }}
                {{- if .Values.daml.rpc.extra_args.enabled }}
                {{ .Values.daml.rpc.extra_args.arg_str }} \
                {{- end }}
              ;
          env:
            - name: POSTGRES_URL
              value: {{ .Values.daml.rpc.postgres_url }}
            {{ if .Values.daml.rpc.env }}
            {{- toYaml .Values.daml.rpc.env | nindent 12 }}
            {{ end }}
          volumeMounts:
            {{- if .Values.besu.privacy.enabled }}
            - mountPath: /config
              name: config
              readOnly: true
            {{- end }}
            - mountPath: /keys
              name: networkkeys-config
              readOnly: true
            - mountPath: /besu-keys
              name: besu-keys
              readOnly: true
            - mountPath: /secrets/jwt
              name: jwt-secret
            {{- include "lib.volumeMounts" .Values.extraVolumeMounts | nindent 12 }}
            {{- include "lib.volumeMounts" .Values.daml.extraVolumeMounts | nindent 12 }}
          resources: {{ toYaml .Values.daml.rpc.resources | nindent 12 }}
      initContainers:
      {{- if .Values.besu.privacy.enabled }}
        - name: rpc-init
          image: "{{.Values.k8s.image.repository }}:{{ .Values.k8s.image.tag }}"
          imagePullPolicy: {{ .Values.besu.image.imagePullPolicy }}
          command:
            - bash
            - -xc
          args:
            - |
              echo "{ \"participants\": [ { \
                \"name\": \"{{.Values.daml.rpc.participantId}}\"", \
                \"participant\": \"{{.Values.daml.rpc.participantId }}\"", \
                \"besuPublicKey\": \"$(cat /keys/{{ include "daml.fullname" .}}-rpc-0.pub)\", \
                \"orionPublicKey\": \"$(cat /enclave/orion.pub)\" }, {\
                \"name\": \"{{ include "daml.repeater.participantId" . }}\", \
                \"participant\": \"{{ include "daml.repeater.participantId" . }}\", \
                \"besuPublicKey\": \"$(cat /keys/{{ include "daml.fullname" .}}-repeater.pub)\", \
                \"orionPublicKey\": \"$(cat /enclave/orion.pub)\" } ] }" > /config/config.json
          volumeMounts:
            - mountPath: /keys
              name: networkkeys-config
              readOnly: true
            - mountPath: /besu-keys
              name: besu-keys
              readOnly: true
            - mountPath: /enclave
              name: enclave
            - mountPath: /repeater
              name: repeater-enclave
            - mountPath: /config
              name: config
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: networkkeys-config
          secret:
            secretName: {{include "daml.fullname" .}}-rpc-keys
        - name: besu-keys
          secret:
            secretName: {{include "besu.fullname" .}}-keys
        - name: jwt-secret
          secret:
            secretName: {{ .Values.deployment.name }}-cert
        {{- if .Values.besu.privacy.enabled }}
        - name: enclave
          configMap:
            name: {{ include "besu.enclave.key.configmap" . }}
        - name: repeater-enclave
          configMap:
            name: {{ include "besu.repeater.key.configmap" . }}
        - name: config
          emptyDir: {}
        {{ end }}
        {{- include "lib.volumes" .Values.extraVolumes | nindent 8 }}
        {{- include "lib.volumes" .Values.daml.extraVolumes | nindent 8 }}
{{- if .Values.postgres.enabled }}
{{- if not .Values.postgres.persistence.enabled }}
        - name: "pgdata"
          emptyDir: {}
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: "pgdata"
        {{- if .Values.postgres.persistence.annotations }}
        annotations: {{- toYaml .Values.postgres.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes: {{- toYaml .Values.postgres.persistence.accessModes | nindent 10 }}
        storageClassName: {{ default "gp2" .Values.postgres.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size | quote }}
{{- end }}
{{- end }}
