{{- $serviceName := include "daml.fullname" . -}}
{{- $ingressName := printf "%s" $serviceName -}}
{{- $servicePort := .Values.daml.jsonapi.port -}}
{{ include "lib.ingress" (dict "ingressName" $ingressName "ingress" .Values.daml.jsonapi.ingress "serviceName" $serviceName "servicePort" $servicePort "context" $) }}
