# kubetpl:syntax:go-template
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}-dep
  namespace: {{.Values.deployment.namespace}}
  labels:
    app: {{.Values.deployment.name}}-validator
    daml: {{.Values.deployment.name}}-daml-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.deployment.name}}-validator
      daml: {{.Values.deployment.name}}-daml-rpc
  template:
    metadata:
      labels:
        app: {{.Values.deployment.name}}-validator
        daml: {{.Values.deployment.name}}-daml-rpc
    spec:
      serviceAccountName: {{.Values.deployment.name}}-sa
      {{ if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
      {{range .Values.imagePullSecrets.value }}
        - name: {{ .name }}
      {{ end }}
      {{ end }}
      containers:
        - name: postgres
          image: {{.Values.images.postgres}}
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        - name: daml-on-qldb
          image: {{.Values.images.damlqldb}}
          imagePullPolicy: Always
          ports:
            - containerPort: 39000
          command: [ "bash","-xc"]
          args:
            - |
              sleep 30
              /opt/daml-on-qldb/entrypoint.sh --port 39000 \
                --jdbc-url jdbc:postgresql://localhost/postgres?user=postgres \
                --ledger ${LEDGER_ID} \
                --participant-id daml-on-qldb-participant \
                {{- if .Values.daml.auth.enabled }}
                --auth-jwt-rs256-crt /secrets/jwt/jwt.crt \
                {{- end }}
                {{- if .Values.daml.extra_args }}
                {{ .Values.daml.extra_args }} \
                {{- end }}
              ;
          env:
            - name: LEDGER_ID
              value: {{.Values.daml.ledgerId}}
          volumeMounts:
            - mountPath: /secrets/jwt
              name: jwt-secret
      volumes:
        - name: jwt-secret
          secret:
            secretName: {{.Values.deployment.name}}-cert

---
