---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "daml.jsonapi.service.name" . }}
  labels: {{ include "daml.labels" . | nindent 4 }}
    component: jsonapi
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.jsonapi.port }}
      protocol: TCP
      targetPort: {{ .Values.jsonapi.port }}
      name: jsonapi
  selector: {{ include "daml.labels.matchLabels" . | nindent 4 }}
    component: jsonapi
