apiVersion: v1
kind: Service
metadata:
  name: {{ template "sextant.fullname" . }}
  labels:
{{ include "sextant.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "sextant.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
