apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
{{ include "lib.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
{{ include "lib.labels" . | indent 4 }}
