apiVersion: v1
clusters:
  - cluster:
      server: https://localhost
    name: dummy
contexts:
  - context:
      cluster: dummy
      user: dummy
    name: dummy
current-context: dummy
kind: Config
preferences: {}
users:
  - name: dummy
