---
{{- $serviceName := include "common.names.fullname" . -}}
{{- $ingressName := printf "%s" $serviceName -}}
{{- $servicePort := .Values.orion.nodeport -}}
{{ include "lib.ingress" (dict "ingressName" $ingressName "ingress" .Values.ingress "serviceName" $serviceName "servicePort" $servicePort "context" $) }}
