---
apiVersion: v1
kind: Service
metadata:
  labels:
{{include "common.labels" . | indent 4 }}
  name: {{ include "common.fullname" . }}
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  selector: {{ include "common.selectorLabels" . | nindent 4 }}
  ports: {{ include "orion.svc.ports" . | nindent 4 }}
