---
{{- if .Values.daml.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "daml.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
{{- if .Values.imagePullSecrets.enabled }}
imagePullSecrets:
{{- range .Values.imagePullSecrets.value }}
  - name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
