---
apiVersion: v1
kind: Service
metadata:
  labels: {{include "daml.labels" . | nindent 4 }}
    component: daml
  name: {{ include "daml.fullname" . }}
  namespace: {{.Release.Namespace}}
spec:
  sessionAffinity: ClientIP
  selector:
{{include "daml.selectorLabels" . | indent 4 }}
  ports:
    - name: daml-rpc
      port: {{.Values.daml.rpc.port}}
      targetPort: {{.Values.daml.rpc.port}}
    - name: jsonapi
      port: {{.Values.daml.jsonapi.ports.http }}
      targetPort: {{.Values.daml.jsonapi.ports.http }}
