@startuml sawtooth-sts

' Kubernetes
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!include KubernetesPuml/kubernetes_Common.puml
!include KubernetesPuml/kubernetes_Context.puml

!include KubernetesPuml/OSS/KubernetesDeploy.puml
!include KubernetesPuml/OSS/KubernetesSts.puml
!include KubernetesPuml/OSS/KubernetesDs.puml
!include KubernetesPuml/OSS/KubernetesSvc.puml
!include KubernetesPuml/OSS/KubernetesPvc.puml
!include KubernetesPuml/OSS/KubernetesPod.puml
!include KubernetesPuml/OSS/KubernetesCm.puml
!include KubernetesPuml/OSS/KubernetesJob.puml


Namespace_Boundary(besuns,"sawtooth") {
  !include sawtooth-sts-unboxed.plantuml
}

actor actor
actor --> sawtooth_svc
actor --> sawtooth_svc_0
actor --> sawtooth_svc_1
actor --> sawtooth_svc_2
actor --> sawtooth_svc_3

@enduml
