---
ordererca:
  enabled: true
  ca:
    name: ordererca

global: {}

imagePullSecrets:
  ## @md | imagePullSecrets.enabled | if imagePullSecrets are provided | false |
  enabled: false
  ## @md | imagePullSecrets.value | a list of names of imagePullSecrets | [] |
  value: []

# image:
#   repository: hyperledger/fabric-ca
#   tag: 1.5.3
#   pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name:

image:
  repository: hyperledger/fabric-orderer
  tag: 2.2.8
  pullPolicy: IfNotPresent

admin:
  port: 9443

logLevel: INFO

mspId: OrdererMSP

operations:
  port: 8443

port: 6050

tools:
  image:
    repository: hyperledger/fabric-tools
    tag: 2.2.8
    pullPolicy: IfNotPresent

caClient:
  image:
    repository: hyperledger/fabric-ca
    tag: 1.5.3
    pullPolicy: IfNotPresent
