---
apiVersion: v2
name: orion
description: |
  Orion is an Apache 2.0 licensed, private transaction manager.

type: application

version: 0.1.1

appVersion: 21.1.0

dependencies:
  - condition: postgresql.create
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ~10.9.2
  - name: standard-defs
    version: ~0.1.0
    repository: https://btp-charts-unstable.s3.amazonaws.com/charts/
