---
## @md # Orion Chart
## @md
## @md ## Configuration
## @md
## @md | field | description | type | default |
## @md |- |- |- |- |

imagePullSecrets:
  enabled: false
  value: []

global:
  image:
    registry: index.docker.io
  postgresql:
    servicePort: ""

orion:
  affinity: {}
  annotations:
    foo: bar
  clientport: 8888
  clientnetworkinterface: 0.0.0.0
  image:
    pullPolicy: IfNotPresent
    repository: consensys/quorum-orion
    tag: "21.1.1"
  # storage="sql:jdbc:postgresql://<HOST>:<PORT>/<DATABASE-NAME>"
  # user=<USER-NAME>&password=<PASSWORD>
  storage: "postgres" # postgres, oracle, leveldb, memory
  nodeport: 8080
  nodenetworkinterface: 0.0.0.0
  othernodes: []
  persistence:
    enabled: false
    annotations: {}
    accessModes:
      - "ReadWriteOnce"
    storageClass:
    size: "40Gi"
  replicas: 2
  resources: {}

serviceAccount:
  create: true
  name:

utils:
  k8s:
    image:
      pullPolicy: IfNotPresent
      repository: alpine/k8s
      tag: "1.20.4"

postgresql:
  create: true
  postgresqlDatabase: "orion"
  postgresqlUsername: "orion"
  host:
  existingSecret: ""
  postgresqlPassword: ""
  servicePort: ""
  replicationPassword: ""
  initdbScripts:
    init.sql: |
      CREATE TABLE store (
        key char(60),
        value bytea,
        primary key(key)
      );
