apiVersion: v2
name: fluentd
description: Fluentd is an open source data collector for unified logging layer

# Replaces the index.js in the deployment templates directory, sawtooth/index
# The deploymentType and deploymentVersion help build the object structure
deploymentType: fluentd
deploymentVersion: 1.11

# absolute path to form.js
form: fluentd/sextant/form.js

# absolute path to summary.jst
summary: fluentd/sextant/summary.js

# paths to be used in the getField function
namePath: deployment.name
namespacePath: deployment.namespace

# additional fields for the button
# form: <same as deploymentVersion>
title: Fluentd
sextantVersion: 1.11
buttonIcon:
features:

# documentation pull down mark down
