@startuml orion

' Kubernetes
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!include KubernetesPuml/kubernetes_Common.puml
!include KubernetesPuml/kubernetes_Context.puml
!include KubernetesPuml/OSS/KubernetesDeploy.puml
!include KubernetesPuml/OSS/KubernetesSts.puml
!include KubernetesPuml/OSS/KubernetesSvc.puml
!include KubernetesPuml/OSS/KubernetesPvc.puml
!include KubernetesPuml/OSS/KubernetesPod.puml
!include KubernetesPuml/OSS/KubernetesCm.puml
!include KubernetesPuml/OSS/KubernetesJob.puml


Namespace_Boundary(daml,"orion") {
  !include orion-unboxed.plantuml
}

actor actor
actor --> orionsvc
actor --> orionsvc0
actor --> orionsvc1

@enduml
