@startuml daml-unboxed

' Kubernetes
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!include KubernetesPuml/kubernetes_Common.puml
!include KubernetesPuml/kubernetes_Context.puml

!include KubernetesPuml/OSS/KubernetesDeploy.puml
!include KubernetesPuml/OSS/KubernetesSts.puml
!include KubernetesPuml/OSS/KubernetesSvc.puml
!include KubernetesPuml/OSS/KubernetesPvc.puml
!include KubernetesPuml/OSS/KubernetesPod.puml
!include KubernetesPuml/OSS/KubernetesCm.puml
!include KubernetesPuml/OSS/KubernetesJob.puml

KubernetesSts(damlrpc, "daml-rpc", "provides the particiant ledger api")

together {
  KubernetesSvc(damlgrpc,"grpc","tcp:39000")
  KubernetesSvc(damljsonapi,"jsonapi","http:8080")
}

damlgrpc --> damlrpc
damljsonapi --> damlrpc

@enduml
