apiVersion: v2
name: daml-on-qldb
description: The DAML smart contract runtime engine with AWS QLDB as the ledger.

# Replaces the index.js in the deployment templates directory, sawtooth/index
# The deploymentType and deploymentVersion help build the object structure
deploymentType: daml-on-qldb
deploymentVersion: 1.3

# absolute path to form.js
form: daml-on-qldb/sextant/form.js

# absolute path to summary.jst
summary: daml-on-qldb/sextant/summary.js

# paths to be used in the getField function
namePath: deployment.name
namespacePath: deployment.namespace

# additional fields for the button
# form: <same as deploymentVersion>
title: DAML on QLDB
sextantVersion: daml-on-qldb(Early Access), AWS QLDB, DAML 0.13.41
buttonIcon: /thirdParty/daml.png
features:
  - daml.parties
  - daml.archives
