apiVersion: v2
name: tfs-on-sawtooth
description: BTP's TFS distribution based on Hyperledger Sawtooth 1.1

type: application

version: 0.6.4

appVersion: 1.3.0

dependencies:
  - name: sawtooth
    version: ~0.2.0
    repository: https://btp-charts-unstable.s3.amazonaws.com/charts/
