## @md # TFS on Sawtooth

global:
  image:
    tag:

imagePullSecrets:
  enabled: false
  value: []

tp:
  args:
  env:
  image:
    pullPolicy: IfNotPresent
    repository: taekion/taekion-fs-tp
    tag: "v0.6.0"
  resources:

maxUnavailable: 1
minReadySeconds: 120

middleware:
  args:
  env:
  image:
    pullPolicy: IfNotPresent
    repository: taekion/taekion-fs-middleware
    tag: "v0.6.0"
  port: 8000
  resources:

perNodeServiceType: ClusterIP
podAnnotations: {}

serviceAccount:
  create: true
  name:

sawtooth:
  sawtooth:
    statefulset:
      enabled: true
    consensus: 400
