## @md # TFS on Sawtooth

global:
  image:
    tag:

imagePullSecrets:
  enabled: false
  value: []

ingress:
  ## @md | `ingress.apiVersion` | if necessary the apiVersion of the ingress may be overridden | "" |
  apiVersion: ""
  ## @md | `ingress.enabled` | true to enable the ingress to the main service rest-api | false |
  enabled: false
  ## @md | `ingress.certManager` | true to enable the acme certmanager for this ingress | false |
  certManager: false
  ## @md | `ingress.hostname` | primary hostname for the ingress | false |
  hostname: "tfs.local"
  ## @md | `ingress.path` | path for the ingress's primary hostname | / |
  path: /
  ## @md | `ingress.pathType` | pathType for the ingress's primary hostname | nil |
  pathType:
  ## @md | `ingress.annotations` | annotations for the ingress | {} |
  annotations: {}
  ## @md | `ingress.tls` | true to enable tls on the ingress with a secrete at hostname-tls | false |
  tls: false
  ## @md | `ingress.extraHosts` | list of extra hosts to add to the ingress | [] |
  extraHosts: []
  ## @md | `ingress.extraPaths` | list of extra paths to add to the primary host of the ingress | [] |
  extraPaths: []
  ## @md | `ingress.extraTls` | list of extra tls entries | [] |
  extraTls: []

tp:
  args:
  env:
  image:
    pullPolicy: IfNotPresent
    repository: taekion/taekion-fs-tp
    tag: "v0.6.0"
  resources:

maxUnavailable: 1
minReadySeconds: 120

middleware:
  args:
  env:
  image:
    pullPolicy: IfNotPresent
    repository: taekion/taekion-fs-middleware
    tag: "v0.6.0"
  port: 8000
  resources:

perNodeServiceType: ClusterIP
podAnnotations: {}

serviceAccount:
  create: true
  name:

sawtooth:
  sawtooth:
    statefulset:
      enabled: true
    consensus: 400
