{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openebs.serviceAccountName" . }}
  labels:
    app: {{ template "openebs.name" . }}
    chart: {{ template "openebs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.imagePullSecrets.enabled }}
imagePullSecrets:
{{- range .Values.imagePullSecrets.value }}
  - name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
