kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Name}}-rb
  namespace: {{.Release.Namespace}}
subjects:
- kind: ServiceAccount
  name: {{.Release.Name}}-sa
  namespace: {{.Release.Namespace}}
- kind: ServiceAccount
  namespace: {{.Release.Namespace}}
  name: default
roleRef:
  kind: Role
  name: {{.Release.Name}}-r
  apiGroup: rbac.authorization.k8s.io
