@startuml besu-private

' Kubernetes
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!include KubernetesPuml/kubernetes_Common.puml
!include KubernetesPuml/kubernetes_Context.puml

!include KubernetesPuml/OSS/KubernetesDeploy.puml
!include KubernetesPuml/OSS/KubernetesSts.puml
!include KubernetesPuml/OSS/KubernetesSvc.puml
!include KubernetesPuml/OSS/KubernetesPvc.puml
!include KubernetesPuml/OSS/KubernetesPod.puml
!include KubernetesPuml/OSS/KubernetesCm.puml
!include KubernetesPuml/OSS/KubernetesJob.puml

Namespace_Boundary(besuns,"besu") {
  !include ../../orion/diagrams/orion-unboxed.plantuml
  !include besu-unboxed.plantuml
}

actor actor
actor --> besusvc
actor --> besusvc0
actor --> besusvc1
actor --> besusvc2
actor --> besusvc3

besu0 --> orionsvc
besu1 --> orionsvc
besu2 --> orionsvc
besu3 --> orionsvc

@enduml
