apiVersion: v2
name: nginx-ingress
version: 0.0.2
appVersion: 1.0.1
description: NGINX Ingress Controller with Sextant customizations
icon: https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v1.8.1/deployments/helm-chart/chart-icon.png
keywords:
  - ingress
  - nginx
maintainers:
  - name: NGINX Kubernetes Team
    email: kubernetes@nginx.com

dependencies:
  - name: ingress-nginx
    version: "~4.0.2"
    repository: https://kubernetes.github.io/ingress-nginx
