---
apiVersion: v2
name: sawtooth
description: BTP's Sawtooth distribution based on Hyperledger Sawtooth 1.2
type: application
version: 0.2.10
appVersion: 1.2.5p4

dependencies:
  - name: standard-defs
    version: ~0.1.0
    repository: https://btp-charts-stable.s3.amazonaws.com/charts/
