{{- if .Values.ingress.enabled -}}
{{- $serviceName := printf "%s-0" (include "common.names.fullname" .) -}}
{{- $ingressName := printf "%s" $serviceName -}}
{{- $servicePort := .Values.middleware.port -}}
{{ include "lib.ingress" (dict "ingressName" $ingressName "ingress" .Values.ingress "serviceName" $serviceName "servicePort" $servicePort "context" $) }}
{{- end -}}
