
{{ $kind := include "tfs.kind" . }}
{{- if eq $kind "StatefulSet" -}}
{{- $ctx := . -}}
{{ range untilStep 0 ((include "tfs.replicas" $ctx) | int) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ctx }}-{{ . }}
  namespace: {{ $ctx.Release.Namespace }}
  labels: {{- include "lib.labels" $ctx | nindent 4 }}
    per-node: {{ include "common.names.fullname" $ctx }}-{{ . }}
    component: tfs
spec:
  sessionAffinity: ClientIP
  type: {{ $ctx.Values.perNodeServiceType }}
  ports:
    - port: {{ $ctx.Values.middleware.port }}
      protocol: TCP
      targetPort: {{ include "tfs.middleware.containerPort" $ctx }}
      name: taekion-rest
    - port: {{ $ctx.Values.s3.port }}
      protocol: TCP
      targetPort: {{ include "tfs.s3.containerPort" $ctx }}
      name: taekion-s3
  selector: {{- include "common.labels.matchLabels" $ctx | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "common.names.fullname" $ctx }}-{{ . }}
{{- end -}}
{{- end -}}
