
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "lib.labels" . | nindent 4 }}
    component: tfs
spec:
  sessionAffinity: ClientIP
  ports:
    - port: {{.Values.middleware.port}}
      protocol: TCP
      targetPort: {{ include "tfs.middleware.containerPort" . }}
      name: taekion-rest
    - port: {{.Values.s3.port}}
      protocol: TCP
      targetPort: {{ include "tfs.s3.containerPort" . }}
      name: taekion-s3
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    component: tfs
