{{ $stlServiceName := include "lib.call-nested" (list . "sawtooth" "common.names.fullname")}}
{{ $kind := include "tfs.kind" . }}
---
apiVersion: apps/v1
kind: {{ include "tfs.kind" . }}
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "lib.labels" . | nindent 4}}
    component: tfs
spec:
  {{ if eq $kind "StatefulSet" -}}
  replicas: {{ include "tfs.replicas" . }}
  serviceName: {{ include "common.names.fullname" . | quote }}
  podManagementPolicy: Parallel
  {{- end }}
  updateStrategy:
    type: RollingUpdate
    {{ if eq $kind "DaemonSet" -}}
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable | int }}
    {{- end }}
  {{ if (semverCompare "^1.22" .Capabilities.KubeVersion.Version) -}}
  minReadySeconds: {{ .Values.minReadySeconds | int }}
  {{- end }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6}}
      component: tfs
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
        component: tfs
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lib.serviceAccountName" . }}
      affinity: {{- include "tfs.affinity" . | nindent 8 }}
      hostAliases:
      containers:
        - name: taekion-tp
          {{- include "lib.image" (dict "imageRoot" .Values.tp.image "global" .Values.global ) | nindent 10 }}
          command: [ "bash", "-c"]
          args:
            - |
              {{ if ne $kind "DaemonSet" -}}
              HOST={{ $stlServiceName }}-${HOST##*-}.{{ .Release.Namespace }}.svc.cluster.local
              {{- end }}
              taekion-fs-tp {{ .Values.tp.args }} -C tcp://$HOST:{{ include "tfs.sawtooth.sawcomp" . }}
          resources: {{- toYaml .Values.tp.resources | nindent 12 }}
          env:
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: {{ include "tfs.field.node" . }}
            {{- include "lib.safeToYaml" .Values.tp.env | nindent 12 }}
          volumeMounts:
            {{- include "lib.volumeMounts" .Values.extraVolumeMounts | nindent 12 }}
        {{- if .Values.s3.enabled }}
        - name: taekion-fs-s3
          {{- include "lib.image" (dict "imageRoot" .Values.s3.image "global" .Values.global ) | nindent 10 }}
          command: [ "bash", "-c"]
          args:
            - |
              {{ if ne $kind "DaemonSet" -}}
              HOST={{ $stlServiceName }}-${HOST##*-}
              {{- end }}
              export TFS_URL=http://$HOST:{{ include "tfs.sawtooth.restport" . }}
              /usr/local/bin/tfs-s3 {{ .Values.s3.args }}
          ports:
            - containerPort: {{ include "tfs.s3.containerPort" . }}
              name: taekion-s3
              {{ if eq $kind "DaemonSet" -}}
              hostPort: {{ include "tfs.s3.containerPort" . }}
              {{- end }}
          resources: {{- toYaml .Values.s3.resources | nindent 12 }}
          env:
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: {{ include "tfs.field.node" . }}
            {{- include "lib.safeToYaml" .Values.s3.env | nindent 12 }}
          volumeMounts:
            {{- include "lib.volumeMounts" .Values.extraVolumeMounts | nindent 12 }}
        {{- end }}
        - name: taekion-rest-api
          {{- include "lib.image" (dict "imageRoot" .Values.middleware.image "global" .Values.global ) | nindent 10 }}
          ports:
            - containerPort: {{ include "tfs.middleware.containerPort" . }}
              name: taekion-rest
              {{ if eq $kind "DaemonSet" -}}
              hostPort: {{ include "tfs.middleware.containerPort" . }}
              {{- end }}
          command: [ "bash", "-c" ]
          args:
            - |
              {{ if ne $kind "DaemonSet" -}}
              HOST={{ $stlServiceName }}-${HOST##*-}
              {{- end }}
              /usr/local/bin/tfs-mid {{ .Values.middleware.args }} --url http://$HOST:{{ include "tfs.sawtooth.restport" . }}
          env:
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: {{ include "tfs.field.node" . }}
            {{- include "lib.volumeMounts" .Values.middleware.env | nindent 12 }}
          resources: {{- toYaml .Values.middleware.resources | nindent 12 }}
          volumeMounts:
            {{- include "lib.volumeMounts" .Values.extraVolumeMounts | nindent 12 }}
      volumes:
        {{- include "lib.volumes" .Values.extraVolumes | nindent 8 }}
