sextant:
  images:
  # Set an image to use for the API container, or remove to use default image
    api: blockchaintp/sextant-api-aws-sfs:BTP2.0.7
  # Set an image to use for the UI container, or delete to use default image
    ui: blockchaintp/sextant-sfs:BTP2.0.7
    noxy: blockchaintp/noxy:BTP2.0.7
  nameOverride: sextant-sfs
