---
## @md # Chronicle on Sawtooth Chart
## @md
## @md | field | description | default |
## @md |-|-|-|

global:
  image:
    tag:

imagePullSecrets:
  ## @md | `imagePullSecrets.enabled`| if true use the list of named imagePullSecrets| false |
  enabled: true
  ## @md | `imagePullSecrets.value`| a list if named secret references of the form `- name: secretName`| [] |
  value:
    - name: regcred

image:
  ## @md | `chronicle.image.repository` | the repository of the image|
  ## blockchaintp/chronicle |
  repository: dev.catenasys.com:8083/base/catenasys/chronicle/chronicle
  ## @md | `chronicle.image.tag`| the tag of the image to use| latest |
  tag: 0.2.0-42-g1505742
  ## @md | `chronicle.image.pullPolicy` | the image pull policy to use| IfNotPresent |
  pullPolicy: Always
logLevel: info

## @md | `chronicle.webUi` | Serve the graphql playground interface if set |false |
webUi: true
namespaces: {}
persistence:
  enabled: true
  annotations:
  accessModes:
    - "ReadWriteOnce"
  storageClass:
  size: 40Gi
volumes: {}
replicas: 2

## @md | `affinity`| custom affinity rules for the chronicle pod | {} |
affinity: {}

## @md | `extraVolumes` | a list of additional volumes to add to chronicle | `[]` |
extraVolumes: []
## @md | `extraVolumeMounts` | a list of additional volume mounts to add to
## chronicle | `[]` |
extraVolumeMounts: []

## @md | `port` | the port on which the chronicle domain lives
port: 9982

serviceAccount:
  ## @md | `serviceAccount.create` | true to create a service account | false |
  create: true
  ## @md | `serviceAccount.name` | name of the service account | nil (defaults to based on release name) |
  name:

ingress:
  ## @md | `ingress.apiVersion` | if necessary the apiVersion of the ingress may be overridden | "" |
  apiVersion: ""
  ## @md | `ingress.enabled` | true to enable the ingress to the main service rest-api | false |
  enabled: false
  ## @md | `ingress.certManager` | true to enable the acme certmanager for this ingress | false |
  certManager: false
  ## @md | `ingress.hostname` | primary hostname for the ingress | false |
  hostname:
  ## @md | `ingress.path` | path for the ingress's primary hostname | / |
  path: /
  ## @md | `ingress.pathType` | pathType for the ingress's primary hostname | nil |
  pathType:
  ## @md | `ingress.annotations` | annotations for the ingress | {} |
  annotations: {}
  ## @md | `ingress.tls` | true to enable tls on the ingress with a secrete at hostname-tls | false |
  tls: false
  ## @md | `ingress.extraHosts` | list of extra hosts to add to the ingress | [] |
  extraHosts: []
  ## @md | `ingress.extraPaths` | list of extra paths to add to the primary host of the ingress | [] |
  extraPaths: []
  ## @md | `ingress.extraTls` | list of extra tls entries | [] |
  extraTls: []
  ## @md | `ingress.hosts`| list of ingress host and path declarations for the chronicle ingress| [] |
  hosts: []
  # - host: chart-example.local
  #   paths:
  #     - /

## @md | `sawtooth` | sawtooth options may be configured | see [Sawtooth](../sawtooth/README.md) |
sawtooth:
  sawtooth:
    statefulset:
      enabled: true
    consensus: 400

tp:
  ## @md | `tp.args` | a string of arguments to pass to the tp container| nil |
  args:
  image:
    ## @md | `tp.image.pullPolicy` | the image pull policy | IfNotPresent |
    pullPolicy: Always
    ## @md | `tp.image.repository` | the image repository | blockchaintp/chronicle-tp |
    repository: dev.catenasys.com:8083/base/catenasys/chronicle/chronicle-tp
    ## @md | `tp.image.tag` | the image tag | BTP2.1.0 |
    tag: 0.2.0-42-g1505742
  ## @md | `tp.extraVolumes` | extra volumes declarations for the chronicle-tp deployment | list | nil
  extraVolumes:
  ## @md | `tp.extraVolumeMounts` | extra volume mounts for chronicle-tp deployment | list | nil
  extraVolumeMounts:
  resources:
  ## @md | `tp.maxUnavailable` | maximum unavailable nodes during a rolling upgrade |
  maxUnavailable: 1
  ## @md | `tp.minReadySeconds` | minimum time before node becomes available |
  minReadySeconds: 0
  logLevel: info
