---
apiVersion: v1
kind: Service
metadata:
  labels: {{include "besu.labels" . | nindent 4 }}
    component: besu
  name: {{ include "besu.fullname" . }}
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  selector:
    app: {{ include "besu.name" . }}
    release: {{ .Release.Name }}
    component: besu-node
    app.kubernetes.io/name: {{ include "besu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: json-rpc
      port: {{.Values.besu.rpc.port}}
      targetPort: {{.Values.besu.rpc.port}}
    - name: ws
      port: {{ .Values.besu.ws.port }}
      targetPort: ws
      protocol: TCP
    - name: graphql
      port: {{ .Values.besu.graphql.port }}
      targetPort: graphql
      protocol: TCP
    - name: rlpx
      port: {{ .Values.besu.p2p.port }}
      targetPort: rlpx
      protocol: TCP
    - name: discovery
      port: {{ .Values.besu.p2p.port }}
      targetPort: discovery
      protocol: UDP
