---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chronicle.service.name" . }}-chronicle-api
  labels: {{ include "chronicle.labels" . | nindent 4 }}
    component: chronicle
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
      name: chronicle
  selector: {{ include "chronicle.labels.matchLabels" . | nindent 4 }}
    component: chronicle
