---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-peer.names.server" . }}
  namespace: {{.Release.Namespace}}
  labels: {{include "fabric-ca.labels" . | nindent 4 }}
    component: peer
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  selector: {{include "fabric-peer.labels.matchLabels" . | nindent 4 }}
    component: peer
  ports:
    - name: ca
      port: {{.Values.port }}
      targetPort: {{.Values.port}}
