# Default values for sextant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: sextant
  namespace: default

imagePullSecrets:
  enabled: false
  value: []
#    - name: regcred

replicaCount: 1

logging: "1"

ui:
  image:
    repository: dev.catenasys.com:8083/blockchaintp/sextant
    tag: latest
    pullPolicy: IfNotPresent
api:
  image:
    repository: dev.catenasys.com:8083/blockchaintp/sextant-api
    tag: latest
    pullPolicy: IfNotPresent
noxy:
  image:
    repository: dev.catenasys.com:8083/blockchaintp/noxy
    tag: latest
    pullPolicy: IfNotPresent


serviceAccount:
  create: true
  name: sextant

postgres:
  # if enabled we allocate a postgres database here
  enabled: true
  image:
    repository: postgres
    tag: 11
  user: postgres
  host: localhost
  database: postgres
  port: 5432
  password: postgres
  passwordSecret:
  tls:
  persistence:
    enabled: false
    annotations: {}
    accessModes:
      - "ReadWriteOnce"
    storageClass: "gp2"
    size: "40Gi"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
