apiVersion: blockchaintp.com/v1alpha1
kind: Sextant
metadata:
  name: {{ template "sextant.fullname" . }}
  labels:
{{ include "sextant.labels" . | indent 4 }}
spec:
    {{- with .Values.database }}
  database:
{{ toYaml . | indent 4 }}
    {{- end }}
  apiimage: {{.Values.images.api}}
  uiimage: {{.Values.images.ui}}
