---
# yamllint disable rule:line-length
## @md # DAML on Besu Chart
## @md
## @md ## Configuration
## @md
## @md | field | description | default |
## @md |- |- |- |

imagePullSecrets:
  ## @md | imagePullSecrets.enabled | true if imagePullSecrets will be provided | false |
  enabled: false
  ## @md | imagePullSecrets.value | a list of names of imagePullSecrets | [] |
  value: []

deployment:
  name: default
  namespace: default

besu:
  ## @md | `besu.extraVolumeMounts` | extra volume mounts for the besu containers | [] |
  extraVolumeMounts: []
  ## @md | `besu.extraVolumes` | extra volume definitions for the besu set | [] |
  extraVolumes: []
  ## @md | `besu.seedNetwork` | whether or not this is a seed or genesis network | true |
  seedNetwork: true
  ## @md | `besu.seedGenesis` | the genesis configuration used if this is not a seed network | nil |
  seedGenesis:
  ## @md | `besu.additionalBootnodeUrls` | A list of enode defining objects defined as below | `[]` |
  additionalBootnodeUrls: []
  ## @md | `besu.additionalBootnodeUrls[].pubkey` | the public key of the enode url | |
  ## @md | `besu.additionalBootnodeUrls[].host` | the hostname of the enode url (it will be resolved if not an ip) | |
  ## @md | `besu.additionalBootnodeUrls[].port` | the port for the enode url | |
  # - pubkey:  abcdef1234567890
  #   host: somehostname
  #   port: 30303
  persistence:
    ## @md | besu.persistence.enabled | true if the besu persistence will be enabled | true |
    enabled: false
    ## @md | besu.persistence.annotations | annotations to be added to the persistence volume | `{}` |
    annotations: {}
    ## @md | besu.persistence.accessMode | the access mode for the persistence volume | `ReadWriteOnce` |
    accessModes:
      - "ReadWriteOnce"
    ## @md | besu.persistence.storageClass | the storage class for the persistence volume | `gps` |
    storageClass: "gp2"
    ## @md | besu.persistence.size | the size of the persistence volume | `40Gi` |
    size: "40Gi"
  ## @md | besu.resources | the resources to be applied to the besu container | `{}` |
  resources: {}
  serviceAccount:
    ## @md | besu.serviceAccount.create | true if the service account will be created | true |
    create: true
    ## @md | besu.serviceAccount.name | override the name of the service account | nil |
    name:
  ## @md | `besu.nodeCount` | the number of besu nodes to start an initial genesis requires 4 | 4 |
  nodeCount: 4
  ## @md | besu.chainId | the chain id for the besu nodes | "19750424" |
  chainId: "19750424"
  ## @md | besu.dataPath | the path to the data directory. This should not normally be changed | `/data` |
  dataPath: /data
  rpc:
    ## @md | besu.rpc.enabled | true if the besu json-rpc will be enabled | true |
    enabled: true
    ## @md | besu.rpc.host | the address to bind the json-rpc to | `"0.0.0.0"` |
    host: "0.0.0.0"
    ## @md | besu.rpc.api | the list of APIs to expose | `'["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET"]'` |
    api: '["DEBUG", "ETH", "ADMIN", "WEB3", "IBFT", "NET", "EEA", "PRIV"]'
    ## @md | besu.rpc.port | the port to bind the json-rpc | `8545` |
    port: 8545
    ## @md | besu.rpc.corsOrigins | the list of cors origins to allow | `'["all"]'` |
    corsOrigins: '["all"]'
    ## @md | besu.rpc.authenticationEnabled | true if the json-rpc will be authenticated | false |
    authenticationEnabled: false
  ws:
    ## @md | besu.ws.enabled | true if the besu ws listener will be enabled | false |
    enabled: false
    ## @md | besu.ws.api | the list of APIs to expose on the websocket listener | `'["DEBUG", "ETH", "WEB3", "NET"]'` |
    api: '["DEBUG", "ETH", "ADMIN", "WEB3", "IBFT", "NET", "EEA", "PRIV"]'
    ## @md | besu.ws.host | the address to bind the websocket listener to | `"0.0.0.0"` |
    host: "0.0.0.0"
    ## @md | besu.ws.port | the port to bind the websocket listener to | `8546` |
    port: 8546
    ## @md | besu.ws.corsOrigins | the list of cors origins to allow | `'["all"]'` |
    corsOrigins: '["all"]'
    ## @md | besu.ws.authenticationEnabled | true if the websocket will be authenticated | false |
    authenticationEnabled: false
  graphql:
    ## @md | besu.graphql.enabled | true if the graphql listener will be enabled | false |
    enabled: false
    ## @md | besu.graphql.host | the address to bind the graphql listener to | `"0.0.0.0"` |
    host: "0.0.0.0"
    ## @md | besu.graphql.corsOrigins | the list of cors origins to allow | `'["all"]'` |
    corsOrigins: '["all"]'
    ## @md | besu.graphql.port | the port to bind the graphql listener to | `8547` |
    port: 8547
  discovery:
    ## @md | besu.discover.port | the port to bind the discovery listener to | `8549` |
    port: 8549
  metrics:
    ## @md | besu.metrics.enabled | true if the metrics listener will be enabled | false |
    enabled: false
    ## @md | besu.metrics.host | the address to bind the metrics listener to | `"0.0.0.0"` |
    host: "0.0.0.0"
    ## @md | besu.metrics.port | the port to bind the metrics listener to | `9545` |
    port: 9545
  metricsPush:
    ## @md | besu.metricsPush.enabled | true if the metrics push will be enabled | false |
    enabled: false
    ## @md | besu.metricsPush.host | the address to push metrics to | `"5.5.5.5"` |
    host: "5.5.5.5"
    ## @md | besu.metricsPush.port | the port to push metrics to | `9091` |
    port: 9091
    ## @md | besu.metricsPush.interval | the interval to push metrics to | `60` |
    interval: 60
    ## @md | besu.metricsPush.prometheusJob | the name of the prometheus metrics push job | "besu"
    prometheusJob: "besu"
  permissions:
    ## @md | besu.permissions.enabled | true if the permissions will be enabled | false |
    enabled: false
    nodes:
      ## @md | besu.permissions.nodes.enabled | true if the node permissions will be enabled | false |
      enabled: false
      ## @md | besu.permissions.nodes.whitelist | a list of whitelisted enodes | `[]` |
      whitelist: []
      # - "enode://PUBKEY@192.168.0.9:4567"
      # - "enode://PUBKEY@192.169.0.9:4568"
    nodesContract:
      ## @md | besu.permissions.nodesContract.enabled | true if the node contract permissioning contract will be enabled | false |
      enabled: false
      ## @md | besu.permissions.nodesContract.address | address of the nodes permissioning contract | `"0x0000000000000000000000000000000000001234"` |
      address: "0x0000000000000000000000000000000000001234"
    accounts:
      ## @md | besu.permissions.accounts.enabled | true if the account permissions will be enabled | false |
      enabled: false
      ## @md | besu.permissions.accounts.whitelist | a list of whitelisted accounts | `[]` |
      whitelist: ["0x0000000000000000000000000000000000000009"]
  privacy:
    ## @md | besu.privacy.enabled | true if the private transactions are enabled on this node | false |
    enabled: false
    ## @md | besu.privacy.url | the url to the private transaction manager | nil |
    url:
    ## @md | besu.privacy.precompileAddress | the precompiled address of the privacy contract | `9` |
    precompileAddress: 9
    ## @md | besu.privacy.enclaveKeyConfigMap | the name of a configmap containing the enclave public Key | nil |
    enclaveKeyConfigMap:
  genesis:
    ## @md | besu.genesis.ibftBlockPeriodSeconds | the ibft block period in seconds | `2` |
    ibftBlockPeriodSeconds: 2
    ## @md | besu.genesis.ibftEpochLength | the ibft epoch length in blocks | `30000` |
    ibftEpochLength: 30000
    ## @md | besu.genesis.ibftRequestTimeoutSeconds | ibft request timeout  | `10` |
    ibftRequestTimeoutSeconds: 10
  ## @md | besu.genesisFilePath | the path to the genesis file | `"/etc/genesis/genesis.json"` |
  genesisFilePath: /etc/genesis/genesis.json
  ## @md | besu.logging | the logging level | `"info"` |
  logging: "info"
  ## @md | `besu.affinity` | custom affinity rules for the besu statefulset | nil |
  affinity: {}
  image:
    ## @md | `besu.image.repository` | the repository of the besu image | `"dev.catenasys.com:8084/blockchaintp/besu"` |
    repository: dev.catenasys.com:8084/blockchaintp/besu
    ## @md | besu.image.tag | the tag of the besu image | `"BTP2.1.0rc15"` |
    tag: BTP2.1.0rc15
    ## @md | besu.image.imagePullPolicy | the pull policy for the besu image | `"IfNotPresent"` |
    imagePullPolicy: IfNotPresent
  privateImage:
    ## @md | `besu.privateImage.repository` | the repository of the besu image | `"dev.catenasys.com:8084/blockchaintp/besu-private"` |
    repository: dev.catenasys.com:8084/blockchaintp/besu-private
    ## @md | besu.privateImage.imagePullPolicy | the pull policy for the besu image | `"IfNotPresent"` |
    tag: BTP2.1.0rc15
    ## @md | besu.privateImage.imagePullPolicy | the pull policy for the besu image | `"IfNotPresent"` |
    imagePullPolicy: IfNotPresent
  p2p:
    ## @md | besu.p2p.enabled | true if the p2p listener will be enabled | true |
    enabled: true
    ## @md | besu.p2p.discover | true if the p2p discovery will be enabled | true |
    discovery: true
    ## @md | besu.p2p.host | the address to bind the p2p listener to | `"0.0.0.0"` |
    host: "0.0.0.0"
    ## @md | besu.p2p.port | the port to bind the p2p listener to | `30303` |
    port: 30303
    ## @md | besu.p2p.maxPeers | the max number of peers to connect to | `25` |
    maxPeers: 25
  http:
    ## @md | besu.http.whitelist | the list of whitelisted http endpoints | `[*]` |
    whitelist: '["*"]'
  txPool:
    ## @md | besu.txPool.retentionHours | the number of hours to keep transactions in the tx pool | `999` |
    retentionHours: 999
    ## @md | besu.txPool.maxSize | the max number of transactions to keep in the tx pool | `1024` |
    maxSize: 1024

daml:
  ## @md | daml.affinity | custom affinity rules for the daml statefulset | nil |
  affinity: {}
  auth:
    ## @md | daml.auth.enabled | true if authentication is to be enabled | false |
    enabled: false
  privacy:
    enabled: false
  privateImage:
    repository: dev.catenasys.com:8084/blockchaintp/private-rpc
    tag: BTP2.1.0rc15
    imagePullPolicy: IfNotPresent
  image:
    ## @md | daml.image.repository | the repository of the daml rpc image | `"dev.catenasys.com:8084/blockchaintp/rpc"` |
    repository: dev.catenasys.com:8084/blockchaintp/rpc
    ## @md | daml.image.tag | the tag of the daml rpc image | `"BTP2.1.0rc15"` |
    tag: BTP2.1.0rc15
    ## @md | daml.image.imagePullPolicy | the pull policy for the daml rpc image | `"IfNotPresent"` |
    imagePullPolicy: IfNotPresent
  ## @md | `daml.ledgerId` | ledger id for this participant | default-ledger-id |
  ledgerId: default-ledger-id
  ## @md | `daml.annotations` | annotations for the daml rpc statefulset | {} |
  annotations: {}
  ## @md | `daml.rpcCount` | number identical rpc participants to allocate | 1 |
  rpcCount: 1
  repeater:
    ## @md | `daml.repeater.repository` | url of the repeater repository | dev.catenasys.com:8084/blockchaintp/repeater |
    repository: dev.catenasys.com:8084/blockchaintp/repeater
    ## @md | `daml.repeater.tag` | tag of the repeater image | BTP2.1.0rc15 |
    tag: BTP2.1.0rc15
    ## @md | `daml.repeater.pullPolicy` | pullPolicy of the repeater image | BTP2.1.0rc15 |
    pullPolicy: IfNotPresent
    ## @md | `daml.repeater.enabled` | the repeater repeats items from the central committer to the various participants | BTP2.1.0rc15 |
    enabled: false
    ## @md | `daml.repeater.participantId` | the pariticipantId of the central committer | nil |
    participantId:
  rpc:
    ## @md | `daml.rpc.env` | list of environment name/value dicts | nil |
    env:
    ## @md | `daml.rpc.extra_args` | extra arguments settings for daml-rpc | N/A |
    extra_args:
      ## @md | `daml.rpc.extra_args.enabled` | if true add the extra arguments | false |
      enabled: false
      ## @md | `daml.rpc.extra_args.arg_str` | string of extra arguments to add | nil |
      arg_str:
    ## @md | `daml.rpc.participantId` | DAML participant id for this participant | daml-participant |
    participantId: daml-participant
    ## @md | `daml.rpc.port` | DAML grpc listening port | 39000 |
    port: 39000
    ## @md | `daml.rpc.postgres_url` | The URL of the index database as described here https://jdbc.postgresql.org/documentation/80/connect.html | jdbc:postgresql://localhost/postgres?user=postgres |
    postgres_url: jdbc:postgresql://localhost/postgres?user=postgres
    resources: {}
  jsonapi:
    ## @md | `daml.jsonapi.enabled` | Enabled the DAML JSON API | false |
    enabled: false
    image:
      ## @md | `daml.jsonapi.image.repository` | repository for the jsonapi image | blockchaintp/daml-json-api |
      repository: blockchaintp/daml-json-api
      ## @md | `daml.jsonapi.image.tag` | tag for the jsonapi image | BTP2.1.0rc15 |
      tag: BTP2.1.0rc15
      ## @md | `daml.jsonapi.image.pullPolicy` | imagePullPolicy for container | IfNotPresent |
      pullPolicy: IfNotPresent
    ingress:
      ## @md | `daml.jsonapi.ingress.apiVersion` | if necessary the apiVersion of the ingress may be overridden | "" |
      apiVersion: ""
      ## @md | `daml.jsonapi.ingress.enabled` | true to enable the ingress to the main service rest-api | false |
      enabled: false
      ## @md | `daml.jsonapi.ingress.certManager` | true to enable the acme certmanager for this ingress | false |
      certManager: false
      ## @md | `daml.jsonapi.ingress.hostname` | primary hostname for the ingress | false |
      hostname:
      ## @md | `daml.jsonapi.ingress.path` | path for the ingress's primary hostname | / |
      path: /
      ## @md | `daml.jsonapi.ingress.pathType` | pathType for the ingress's primary hostname | nil |
      pathType:
      ## @md | `daml.jsonapi.ingress.annotations` | annotations for the ingress | {} |
      annotations: {}
      ## @md | `daml.jsonapi.ingress.tls` | true to enable tls on the ingress with a secrete at hostname-tls | false |
      tls: false
      ## @md | `daml.jsonapi.ingress.extraHosts` | list of extra hosts to add to the ingress | [] |
      extraHosts: []
      ## @md | `daml.jsonapi.ingress.extraPaths` | list of extra paths to add to the primary host of the ingress | [] |
      extraPaths: []
      ## @md | `daml.jsonapi.ingress.extraTls` | list of extra tls entries | [] |
      extraTls: []
    port: 8080
    ## @md | `daml.jsonapi.args` | extra args | nil |
    args:
    ## @md | `daml.jsonapi.env` | list of environment name/value dicts | nil |
    env:
    ## @md | `daml.jsonapi.packageReloadInterval` | how often to periodically check the daml-rpc for new daml packages | 5s |
    packageReloadInterval: "5s"
    resources: {}
    ## @md | `daml.jsonapi.waitTimeSeconds` | how long to wait for the daml-rpc server to come available | 0 (forever) |
    waitTimeSeconds: 0
  metrics:
    besu:
      enabled: false
      ## @md | `daml.metrics.besu.reporter` | Metrics reporter to use, console: prints captured metrics on the standard output csv://</path/to/metrics.csv>: saves the captured metrics in CSV format at the specified location graphite://<server_host>[:<server_port>]: sends captured metrics to a Graphite server. If the port is omitted, the default value 2003 will be used. prometheus://<server_host>[:<server_port>] | console |
      reporter: "sl4jjson"
      ## @md | `daml.metrics.besu.interval` | Metrics reporting interval, in java duration format | PT10S |
      interval: "PT60S"
    enabled: false
    ## @md | `daml.metrics.reporter` | Metrics reporter to use, console: prints captured metrics on the standard output csv://</path/to/metrics.csv>: saves the captured metrics in CSV format at the specified location graphite://<server_host>[:<server_port>]: sends captured metrics to a Graphite server. If the port is omitted, the default value 2003 will be used. prometheus://<server_host>[:<server_port>] | console |
    reporter: "console"
    ## @md | `daml.metrics.interval` | Metrics reporting interval, in java duration format | PT10S |
    interval: "PT20S"
  ## @md | `daml.extraVolumeMounts` | extra volume mounts for the daml-on-besu container | [] |
  extraVolumeMounts: []
  ## @md | `daml.extraVolumes` | extra volume definitions for the daml-on-besu container | [] |
  extraVolumes: []

## @md | `extraVolumeMounts` | extra volume mounts for all sets | [] |
extraVolumeMounts: []
## @md | `extraVolumes` | extra volume definitions for all sets | [] |
extraVolumes: []

orion:
  ## @md | orion.create | if true, an orion instance will be created, and used if `besu.privacy.enabled==true` | false |
  create: false

postgres:
  # If true dynamically allocate a postgres database, otherwise expect
  # configuration details
  ## @md | postgres.enabled | true if the embedded postgres will be enabled | true |
  enabled: true
  image:
    ## @md | postgres.image.repository | the docker image repository | postgres |
    repository: postgres
    ## @md | postgres.image.tag | the docker image tag | latest |
    tag: "11"
    ## @md | postgres.image.pullPolicy | the docker image pull policy | IfNotPresent |
    pullPolicy: IfNotPresent
  ## #md | postgres.host | the postgres host | localhost |
  host: localhost
  ## #md | postgres.port | the postgres port | 5432 |
  port: 5432
  ## #md | postgres.user | the postgres user | postgres |
  user: postgres
  ## #md | postgres.database | the postgres database | postgres |
  database: postgres
  ## #md | postgres.password | the postgres password | '' |
  password: ""
  ## #md | postgres.existingPasswordSecret | the name of an existing password secret | '' |
  existingPasswordSecret: ""

  persistence:
    ## @md | postgres.persistence.enabled | true if the postgres persistence will be enabled | true |
    enabled: false
    annotations: {}
    ## @md | postgres.persistence.accessModes | the access modes for the postgres persistence | ["ReadWriteOnce"] |
    accessModes:
      - "ReadWriteOnce"
    resources: {}
    ## @md | postgres.persistence.storageClass | the name of the storage class | "gp2" |
    storageClass: "gp2"
    ## @md | postgres.persistence.size | the size of the postgres persistence | 10Gi |
    size: "40Gi"

openssl:
  image:
    ## @md | openssl.image.repository | the docker image repository | openssl |
    repository: alpine/openssl
    ## @md | openssl.image.tag | the docker image tag | latest |
    tag: latest
k8s:
  image:
    ## @md | k8s.image.repository | the docker image repository | kubernetes |
    repository: alpine/k8s
    ## @md | k8s.image.tag | the docker image tag | latest |
    tag: 1.18.2
