---
## @md # DAML on Besu Chart
## @md
## @md ## Configuration
## @md
## @md | field | description | type | default |
## @md |- |- |- |- |

imagePullSecrets:
  enabled: false
  value:
    - name: regcred
deployment:
  name: default
  namespace: default
## @md |`besu` | besu settings | map | N/A |
besu:
  ## @md | `besu.seedNetwork` | whether or not this is a seed or genesis network | boolean | true |
  seedNetwork: true
  ## @md | `besu.seedGenesis` | the genesis configuration used if this is not a seed network | string | nil |
  seedGenesis:
  ## @md | `besu.additionalBootnodeUrls` | A list of enode defining objects defined as below | list | `[]` |
  additionalBootnodeUrls: []
    ## @md | `besu.additionalBootnodeUrls[].pubkey` | the public key of the enode url | string | |
    ## @md | `besu.additionalBootnodeUrls[].host` | the hostname of the enode url (it will be resolved if not an ip) | string | |
    ## @md | `besu.additionalBootnodeUrls[].port` | the port for the enode url | number | |
    # - pubkey:  abcdef1234567890
    #   host: somehostname
    #   port: 30303
  persistence:
    enabled: false
    annotations: {}
    accessModes:
      - "ReadWriteOnce"
    storageClass: "gp2"
    size: "40Gi"
  resources: {}
  ## @md | `besu.annotations` | annotations for the besu statefulset | map | null |
  annotations: {}
  serviceAccount:
    create: true
    name:
  ## @md | `besu.nodeCount` | the number of besu nodes to start an initial genesis requires 4 | number | 4 |
  nodeCount: 4
  chainId: "19750424"
  dataPath: /data
  rpc:
    enabled: true
    host: "0.0.0.0"
    api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET"]'
    port: 8545
    corsOrigins: '["all"]'
    authenticationEnabled: false
  ws:
    enabled: false
    api: '["DEBUG", "ETH", "WEB3", "NET"]'
    host: "0.0.0.0"
    port: 8546
    corsOrigins: '["all"]'
    authenticationEnabled: false
  graphql:
    enabled: false
    host: "0.0.0.0"
    corsOrigins: '["all"]'
    port: 8547
  discovery:
    port: 8549
  metrics:
    enabled: false
    host: "0.0.0.0"
    port: 9545
  metricsPush:
    enabled: false
    host: "5.5.5.5"
    port: 9091
    interval: 60
    prometheusJob: "besu"
  permissions:
    enabled: false
    nodes:
      enabled: false
      whitelist: []
      # - "enode://PUBKEY@192.168.0.9:4567"
      # - "enode://PUBKEY@192.169.0.9:4568"
    nodesContract:
      enabled: false
      address: "0x0000000000000000000000000000000000001234"
    accounts:
      enabled: false
      whitelist: ["0x0000000000000000000000000000000000000009"]
  privacy:
    enabled: false
    url: "http://127.0.0.1:8888"
    precompileAddress: 9
  genesis:
    ibftBlockPeriodSeconds: 2
    ibftEpochLength: 30000
    ibftRequestTimeoutSeconds: 10
  genesisFilePath: /etc/genesis/genesis.json
  logging: "info"
  ## @md | `besu.affinity` | custom affinity rules for the besu statefulset | map | nil |
  affinity: {}
  image:
    repository: dev.catenasys.com:8084/blockchaintp/besu
    tag: BTP2.1.0rc14
    imagePullPolicy: IfNotPresent
  privateImage:
    repository: dev.catenasys.com:8084/blockchaintp/besu-private
    tag: BTP2.1.0rc14
    imagePullPolicy: IfNotPresent
  p2p:
    enabled: true
    discovery: true
    host: "0.0.0.0"
    port: 30303
    maxPeers: 25
  http:
    whitelist: '["*"]'
  txPool:
    retentionHours: 999
    maxSize: 1024
## @md | `daml` | settings for DAML subsystem | map | N/A |
daml:
  ## @md | `daml.ledgerId` | ledger id for this participant | string | default-ledger-id |
  ledgerId: default-ledger-id
  auth:
    enabled: false
  privacy:
    enabled: false
  privateImage:
    repository: dev.catenasys.com:8084/blockchaintp/private-rpc
    tag: BTP2.1.0rc14
    imagePullPolicy: IfNotPresent
  image:
    repository: dev.catenasys.com:8084/blockchaintp/rpc
    tag: BTP2.1.0rc14
    imagePullPolicy: IfNotPresent
  ## @md | `daml.annotations` | annotations for the daml rpc statefulset | map | null |
  annotations: {}
  ## @md | `daml.rpcCount` | number identical rpc participants to allocate | number | 1 |
  rpcCount: 1
  ## @md | `daml.rpc` | settings for daml-rpc | map | N/A |
  rpc:
    resources: {}
    ## @md | `daml.rpc.extra_args` | extra arguments settings for daml-rpc | map | N/A |
    extra_args:
      ## @md | `daml.rpc.extra_args.enabled` | if true add the extra arguments | boolean | false |
      enabled: false
      ## @md | `daml.rpc.extra_args.arg_str` | string of extra arguments to add | string | nil |
      arg_str:
    ## @md | `daml.rpc.port` | DAML grpc listening port | int | 39000 |
    port: 39000
    postgresqlUrl:
    ## @md | `daml.rpc.participantId` | DAML participant id for this participant | string | daml-participant |
    participantId: daml-participant
postgres:
  persistence:
    enabled: false
    annotations: {}
    accessModes:
      - "ReadWriteOnce"
    resources: {}
    storageClass: "gp2"
    size: "40Gi"
  image:
    repository: postgres
    tag: 11
openssl:
  image:
    repository: alpine/openssl
    tag: latest
k8s:
  image:
    repository: alpine/k8s
    tag: 1.18.2
