---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lib.serviceAccountName" . }}-role
  namespace: {{.Release.Namespace}}
  labels: {{ include "lib.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "" # "" refers to the core API group
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - update
      - patch
      # - delete
  # - apiGroups:
  #     - ""
  #   resources:
  #     - pods
  #   verbs:
  #     - get
  #     - list
  #     - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lib.serviceAccountName" . }}-rb
  namespace: {{.Release.Namespace}}
  labels: {{ include "lib.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lib.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "lib.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
