---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-sa
  namespace: {{ .Release.Namespace }}
{{ if .Values.imagePullSecrets.enabled }}
imagePullSecrets:
{{range .Values.imagePullSecrets.value }}
  - name: {{ .name }}
{{ end }}
{{ end }}
