---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{include "common.fullname" .}}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "sawtooth.labels" . | nindent 4 }}
rules:
  - apiGroups: ["","apps/v1"] # "" refers to the core API group
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["","apps/v1"] # "" refers to the core API group
    resources: ["configmaps"]
    verbs: ["get", "create", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{include "common.fullname" .}}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "sawtooth.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{include "common.fullname" .}}
subjects:
- kind: ServiceAccount
  name: {{ include "common.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
