---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fabric-orderer.names.msp-config" . }}
  labels: {{ include "fabric-orderer.labels" .| nindent 4}}
data:
  config.yaml: |-
    NodeOUs:
      Enable: true
      ClientOUIdentifier:
        Certificate: cacerts/{{ include "fabric-orderer.names.ca" . }}-{{ include "fabric-orderer.names.ca" . }}.pem
        OrganizationalUnitIdentifier: client
      PeerOUIdentifier:
        Certificate: cacerts/{{ include "fabric-orderer.names.ca" . }}-{{ include "fabric-orderer.names.ca" . }}.pem
        OrganizationalUnitIdentifier: peer
      AdminOUIdentifier:
        Certificate: cacerts/{{ include "fabric-orderer.names.ca" . }}-{{ include "fabric-orderer.names.ca" . }}.pem
        OrganizationalUnitIdentifier: admin
      OrdererOUIdentifier:
        Certificate: cacerts/{{ include "fabric-orderer.names.ca" . }}-{{ include "fabric-orderer.names.ca" . }}.pem
        OrganizationalUnitIdentifier: orderer
