---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-orderer.names.server" . }}
  namespace: {{.Release.Namespace}}
  labels: {{include "fabric-ca.labels" . | nindent 4 }}
    component: orderer
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  selector: {{include "fabric-orderer.labels.matchLabels" . | nindent 4 }}
    component: orderer
  ports:
    - name: ca
      port: {{.Values.port }}
      targetPort: {{.Values.port}}
