apiVersion: v2
name: grafana
description: Grafana is an open source, feature rich metrics dashboard and graph editor for Graphite, Elasticsearch, OpenTSDB, Prometheus and InfluxDB.

# Replaces the index.js in the deployment templates directory, sawtooth/index
# The deploymentType and deploymentVersion help build the object structure
deploymentType: grafana
deploymentVersion: 7.1

# absolute path to form.js
form: grafana/sextant/form.js

# absolute path to summary.jst
summary: grafana/sextant/summary.js

# paths to be used in the getField function
namePath: deployment.name
namespacePath: deployment.namespace

# additional fields for the button
# form: <same as deploymentVersion>
title: Grafana
sextantVersion: 7.1
buttonIcon: https://bitnami.com/assets/stacks/grafana/img/grafana-stack-220x234.png
features:

# documentation pull down mark down
