apiVersion: v2
name: daml-on-postgres
description: The Daml smart contract runtime engine with Postgres as the ledger

# Replaces the index.js in the deployment templates directory, sawtooth/index
# The deploymentType and deploymentVersion help build the object structure
deploymentType: daml-on-postgres
deploymentVersion: 1.3

# absolute path to form.js
form: daml-on-postgres/sextant/form.js

# absolute path to summary.jst
summary: daml-on-postgres/sextant/summary.js

# paths to be used in the getField function
namePath: deployment.name
namespacePath: deployment.namespace

# additional fields for the button
# form: <same as deploymentVersion>
title: Daml on Postgres
sextantVersion: Daml 1.13, daml-on-postgres 1.13
buttonIcon: /thirdParty/daml-a.png
features:
  - daml.parties
  - daml.archives

# documentation pull down mark down
